language: python

matrix:
  include:
    - python: 3.7

install:
  - pip install --upgrade pip
  - pip install -r dev-requirements.txt
  - pip install .
  - urduhack download

script:
  - pytest --pylint --cov=./ --ignore=urduhack/tasks

after_success:
  - codecov

notifications:
  slack: urduhack:HarNbK5WrXQbu9XuFLPsSFtM
deploy:
  skip_cleanup: true
  provider: pypi
  distributions: sdist bdist_wheel
  on:
    tags: true
    branch:
      - master
      - /?(\d+\.)?(\d+\.)?(\*|\d+)$/
  user: ${PYPI_USER}
  password: ${PYPI_PASSWORD}
