language: python

matrix:
  include:
    - python: 3.6
    - python: 3.7
    - name: "Python 3.7.4 on macOS"
      os: osx
      osx_image: xcode11.2
      language: shell
    - name: "Python 3.7.0 on Windows"
      os: windows           # Windows 10.0.17134 N/A Build 17134
      language: shell       # 'language: python' is an error on Travis CI Windows
      before_install:
        - choco install python --version 3.7.0
        - python -m pip install --upgrade pip
      env: PATH=/c/Python37:/c/Python37/Scripts:$PATH

install:
  - pip install --upgrade pip
  - pip install -r dev-requirements.txt
  - pip install .
  - urduhack download

script:
  - pytest --cov=./ --ignore=urduhack/tasks
  - codecov

notifications:
  slack: urduhack:HarNbK5WrXQbu9XuFLPsSFtM
deploy:
  skip_cleanup: true
  provider: pypi
  distributions: sdist bdist_wheel
  on:
    tags: true
    branch:
      - master
      - /?(\d+\.)?(\d+\.)?(\*|\d+)$/
  user: ${PYPI_USER}
  password: ${PYPI_PASSWORD}
